//Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
//1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
//By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
package main

import "fmt"

func main() {
	fmt.Println(sum_of_fib(4000000))
}
func sum_of_fib(x int) int {
	var fib_1, fib_2, next_fib, sum int
	fib_1 = 1
	fib_2 = 1
	next_fib = 0
	sum = 0
	for next_fib < x {
		if next_fib%2 == 0 {
			sum += next_fib
		}
		next_fib = fib_1 + fib_2 
		fib_1 = fib_2            
		fib_2 = next_fib         
	}
	return sum
}
